apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
    name: 
    namespace: 
    labels:
    tekton.dev/pipeline: build-deploy-component
    annotations:
    #   pipelinesascode.tekton.dev/on-event: "[incoming]"
    #   pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "[git-clone]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
    timeout: 1h

    # serviceAccountName: build-pipeline-sa

    params:
    - name: repo-url
        value: 
    - name: revision
        value: 
    - name: project-dir
        value: 
    - name: image-url
        value: /
    - name: image-tag
        value: 

    pipelineRef:
    name: trigger-build-component

    workspaces:
    - name: source
        volumeClaimTemplate:
        spec:
            accessModes:
            - ReadWriteOnce
            resources:
            requests:
                storage: 1Gi

    - name: basic-auth
        secret:
        secretName: ""

    # Docker config
    #   - name: docker-config
    #     secret:
    #       secretName: docker-config
