
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-push-image
spec:
  params:
  steps:
  - name: build-and-push
    image: buildpacksio/pack:base
    script: |
      #!/bin/bash
      set -ex

      pack version

      
