
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-push-image
spec:
  params:
  workspaces:
    - name: source
  steps:
  - name: build-and-push
    image: buildpacksio/pack:base
    script: |
      #!/bin/bash
      set -ex

      ls -la $(workspaces.source.path)

      # List all directories with changes and put them in an array
      changed_dirs=()
      while IFS= read -r line; do
          changed_dirs+=("$line")
      done < <(git diff --name-only | xargs -I {} dirname {} | sort -u)


      
