apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: detect-changed-components
  namespace: tekton-pipelines
spec:
  workspaces:
  - name: source
  
  results:
  - name: changed-dirs
    description: All directories with file changes

  steps:
  - name: detect-change
    image: alpine/git:latest
    workingDir: $(workspaces.output.path)
    script: |
      #!/bin/sh
      set -e

      # List all directories with changes in POSIX sh style.
      changed_dirs=$(git diff --name-only | xargs -I {} dirname {} | sort -u | tr '\n' ' ')

      printf '%s' "$changed_dirs" | tee "$(results.changed-dirs.path)"
