apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: main-pipeline
  namespace: tekton-pipelines
spec:
  params:
    - name: repo_url
      description: The repo URL where Git will clone
    - name: revision
      description: Repo's commit SHA

  workspaces:
    - name: source
    - name: basic-auth
    
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
        - name: depth
          value: "0"
      workspaces:
        - name: output
          workspace: source
        - name: basic-auth
          workspace: basic-auth

    - name: detect-changed-components
      taskRef:
        name: detect-changed-components
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source

      # - name: trigger-build-push-changed-components
      #   taskRef:
      #     name: trigger-build
      #   runAfter:
      #     - detect-changed-components
      #   workspaces:
      #     - name: source
      #       workspace: source
      