apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: saritasa-trigger-pipelinerun-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-trigger-pipelines
subjects:
- kind: ServiceAccount
  name: default
  namespace: saritasa-devops-build-samples-pipelines
