apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: tekton-trigger-pipelines
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - taskruns
  - pipelines
  - tasks
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
