apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: saritasa-devops-build-samples
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push, incoming]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "[git-clone]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-path-changed-ignore: "[go.mod, go.sum, LICENSE, NOTICE, README.md, .editorconfig]"
spec:
  params:
    # The variable with brackets are special to Pipelines-as-Code
    # They will automatically be expanded with the events from GitHub.
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineRef:
    name: main-pipeline

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    # This workspace will inject secret to help the git-clone task to be able to
    # checkout the private repositories
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
