apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: build-project-push-run
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[features]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-path-changed-ignore: "[go.mod, go.sum, LICENSE, NOTICE, README.md, .editorconfig]"
spec:
  params:
    # The variable with brackets are special to Pipelines-as-Code
    # They will automatically be expanded with the events from GitHub.
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: git-auth-secret-name
      value: "{{ git_auth_secret }}"
    - name: image-registry
      value: jackdock777
      
  pipelineRef:
    name: build-project

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    # This workspace will inject secret to help the git-clone task to be able to
    # checkout the private repositories
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
