apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: "{{ pipeline_run_name }}"
  namespace: "{{ namespace }}"
  annotations:
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  timeouts:
    pipeline: 1h

  params:
    - name: repo-url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: project-dir
      value: "{{ project_dir }}"
    - name: image-url
      value: "{{ image_url }}"
    - name: image-tag
      value: "{{ image_tag }}"

  # Cluster resolver is used here because this Pipeline template is triggered with K8s native api,
  # so kube-api-server doesn't know how to resolve pipeline reference locally.
  pipelineRef:
    name: build-deploy-single-component
    # resolver: cluster
    # params:
    #   - name: name
    #     value: build-deploy-single-component
    #   - name: namespace
    #     value: tekton-pipelines
    #   - name: kind
    #     value: pipeline

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret_name }}"

    # Docker config
    - name: docker-config
      secret:
        secretName: docker-config
